id: IAEA889A1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-09-24T08:37:51+00:00'
last_modified: '2022-06-13T12:53:15.774146+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21818
  title: ནག་རྩིས་རྡེལ་འགྲེམ་འབྲས་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BD0B:
      image_group_id: I1KG21886
      title: ''
      total_pages: ''
      order: 1
      base_file: BD0B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
