id: 511fadc887f44feebdcb6e827df4252b
initial_creation_type: ocr
created_at: 24/09/2021
last_modified_at: 2021-12-20 10:25:23.514850
source_metadata:
  id: bdr:W1KG21818
  title: ནག་རྩིས་རྡེལ་འགྲེམ་འབྲས་བཤད།
  volumes:
    c4e96e3e8b0545e990a8e59f63a0f148:
      image_group_id: I1KG21886
      title: ''
      base_file: v001.txt
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
